# Generated by Django 4.0.4 on 2022-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolista',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('equipo', models.TextField(default='pendiente', max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_debut', models.DateField(default=None)),
                ('equipo_debut', models.TextField(default=None)),
            ],
        ),
    ]
