# Generated by Django 4.0.4 on 2022-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolista',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('equipo', models.TextField(default='pendiente', max_length=150)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]

